const $=id=>document.getElementById(id);let DATA=[];let STRATS={};let ACTIVE='scalp';
async function j(u){const r=await fetch(u);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function n(v,d=1){return v==null?'—':Number(v).toFixed(d)}
function money(v){v=+v||0;if(v>=1e12)return '$'+(v/1e12).toFixed(2)+'T';if(v>=1e9)return '$'+(v/1e9).toFixed(2)+'B';if(v>=1e6)return '$'+(v/1e6).toFixed(2)+'M';return '$'+v.toLocaleString(undefined,{maximumFractionDigits:8})}
function stage(c){return c.stage==='CONFIRMED_EXPANSION'?'🟢 توسع مؤكد':c.stage==='PRE_BREAKOUT'?'🟨 قبل الاختراق':c.stage==='STEALTH_ACCUMULATION'?'🟦 تجميع خفي':'👀 مراقبة'}
function stat(a,b){return `<div class="stat"><span>${a}</span><b>${b??'—'}</b></div>`}
function card(c,rank='',score=null){let s=score==null?Number(c.early_moon_ratio||c.ai_confidence||0):score;return `<article class="coin ${rank?'main':''}" data-symbol="${esc(c.symbol)}"><div class="coin-top"><span class="rank">${rank||stage(c)}</span><span class="symbol">${esc(c.symbol)}</span></div><div class="price">${money(c.price)}</div><div class="score"><span>قوة الإشارة</span><b>${n(s)}</b></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,s))}%"></i></div><div class="stats">${stat('التجميع',n(c.accumulation))}${stat('CVD/Flow',n(c.cvd))}${stat('السيولة',n(c.liquidity))}${stat('الحيتان',n(c.whale_hunter))}</div><span class="tag">${esc(c.stage_ar||stage(c))}</span><p class="why">${esc((c.why||[]).slice(0,3).join(' • '))}</p><button class="more">🔎 تفاصيل العملة</button></article>`}
const desc={scalp:'⚡ سكالب: 5m + 15m. نركز على CVD، حجم اللحظة، OBV، السيولة، RSI وموقع السعر من المقاومة.',day:'☀️ يومي: 15m + 1h. نركز على التجميع، اتجاه الساعة، التدفق، الحجم والاستعداد للاختراق.',swing:'🌊 سوينغ: 1h + 4h. نركز على الاتجاه الأعلى، OBV، التجميع، موقع السعر والسيولة مع عقوبة التمدد.',invest:'🏦 شهر–شهرين: 4h + 1d. نركز على الاتجاه الأطول، OBV، التجميع، السيولة وتقليل مطاردة الحركة.'};
function renderMode(){let a=STRATS[ACTIVE]||[];$('modeDesc').textContent=desc[ACTIVE];$('modeOut').innerHTML=a.map((c,i)=>card(c,'#'+(i+1),c.strategy_score)).join('')||'<div class="empty">اضغط فحص جديد لتحميل الاستراتيجيات.</div>';bindCards()}
function lanes(){[['stealth','STEALTH_ACCUMULATION'],['prebreak','PRE_BREAKOUT'],['confirmed','CONFIRMED_EXPANSION']].forEach(([id,s])=>{$(id).innerHTML=DATA.filter(c=>c.stage===s).slice(0,5).map((c,i)=>card(c,'#'+(i+1))).join('')||'<div class="empty">لا توجد مطابقة حاليًا.</div>'});bindCards()}
async function scan(){const b=$('scan');b.disabled=true;b.textContent='⏳ جاري الفحص';try{const [d,st]=await Promise.all([j('/api/radar'),j('/api/strategies')]);DATA=d.results||[];STRATS=st.strategies||{};$('bin').textContent=`Binance 🟢 • ${d.scanned_universe||0} زوج`;$('stats').textContent=`آخر تحديث • ${d.scan_seconds||0} ثانية • ${d.deep_analyzed||0} تحليل عميق`;$('top5').innerHTML=(d.top5||DATA.slice(0,5)).slice(0,5).map((c,i)=>card(c,'#'+(i+1))).join('')||'<div class="empty">لا توجد إشارات قوية حاليًا.</div>';lanes();renderMode()}catch(e){$('top5').innerHTML='<div class="empty red">تعذر تحميل الرادار: '+esc(e.message)+'</div>'}finally{b.disabled=false;b.textContent='فحص جديد';bindCards()}}
async function ws(){try{const d=await j('/api/orderflow/status');$('ws').textContent=`البيانات الحية ${d.connected?'🟢 متصلة':'🟡 انتظار'} • ${d.symbols||0} رموز`}catch{$('ws').textContent='البيانات الحية 🔴'}}
function fmt(x){x=+x||0;if(x>=1e12)return(x/1e12).toFixed(1)+'T';if(x>=1e9)return(x/1e9).toFixed(1)+'B';if(x>=1e6)return(x/1e6).toFixed(1)+'M';return Math.round(x)}
function afCard(c,i){return `<article class="coin" data-symbol="${esc(c.symbol)}"><div class="coin-top"><span class="rank">#${i+1} • ${esc(c.acc_flow_state_ar||c.acc_flow_state||'مراقبة')}</span><span class="symbol">${esc(c.symbol)}</span></div><div class="price">${money(c.price)}</div><div class="score"><span>التجميع + التدفق</span><b>${n(c.acc_flow_score)}</b></div><div class="bar"><i style="width:${Math.min(100,+c.acc_flow_score||0)}%"></i></div><div class="stats">${stat('التجميع',n(c.accumulation))}${stat('التدفق',n(c.flow_score))}${stat('CVD',n(c.cvd))}${stat('الحيتان',n(c.whale_hunter))}${stat('حجم/قيمة',n(c.volume_mcap_ratio,2)+'%')}${stat('القيمة السوقية',money(c.market_cap_usd))}</div><span class="tag">${esc(c.utility||'المنفعة غير متحقق منها')}</span><p class="why">${esc(c.core_reason||'')}</p><button class="more">🔎 تفاصيل العملة</button></article>`}
async function af(){let b=$('af');b.disabled=true;b.textContent='⏳ جاري الفحص';try{const d=await j('/api/accflow?core_only=true');if(d.status!=='ok')throw Error(d.error||'خطأ');$('afsummary').innerHTML=`<span>المؤهل: ${d.matched}</span><span>التعميق: ${d.deep_checked}</span><span>القيمة السوقية ≥ $5B</span><span>حجم/قيمة ≥ ${d.core_filter.min_volume_mcap_pct}%</span>`;$('afout').innerHTML=(d.top10||[]).slice(0,5).map(afCard).join('')||'<div class="empty">لا توجد مطابقة حاليًا.</div>';bindCards()}catch(e){$('afout').innerHTML='<div class="empty red">فشل الفحص: '+esc(e.message)+'</div>'}finally{b.disabled=false;b.textContent='فحص الجودة'}}
async function bt(){let b=$('bt');b.disabled=true;b.textContent='⏳ جاري الاختبار';try{const d=await j('/api/backtest/top?top_n=50&days=30');let rows=(d.pattern_leaderboard||[]).slice(0,5).map(x=>`<div class="row"><b>${esc(x.pattern)}</b><span>${x.signals} إشارة</span><span>${x.win_rate}% نجاح</span><span>${x.avg_return_pct}% متوسط</span></div>`).join('');$('btout').innerHTML=`<p>اختُبرت ${d.tested}/${d.top_n} عملة.</p>${rows}`}catch(e){$('btout').innerHTML='<p class="red">فشل الاختبار: '+esc(e.message)+'</p>'}finally{b.disabled=false;b.textContent='اختبر أفضل 50'}}
async function detail(symbol){$('modal').classList.remove('hidden');$('detail').innerHTML='<div class="loading">⏳ جاري جلب التحليل التفصيلي...</div>';try{const d=await j('/api/details/'+encodeURIComponent(symbol));if(d.status!=='ok')throw Error(d.error||'خطأ');let f=d.funding_pct;let fund=f==null?'غير متاح':(f<0?'🟢 '+n(f,4)+'% (سالب)':n(f,4)+'% (موجب)');$('detail').innerHTML=`<div class="detail-head"><div><div class="kicker">تحليل تفصيلي</div><h2>${esc(d.symbol)}</h2><div class="detail-price">${money(d.price)} <small>${n(d.change24h,2)}% خلال 24س</small></div></div><span class="tag">${esc(d.stage||'مراقبة')}</span></div><div class="detail-grid">${stat('التمويل',fund)}${stat('المخاطر',n(d.risk))}${stat('التجميع',n(d.accumulation))}${stat('Early Moon',n(d.early_moon_ratio))}${stat('CVD',n(d.cvd))}${stat('Flow',n(d.flow))}${stat('Whale',n(d.whale))}${stat('السيولة',n(d.liquidity))}${stat('RSI 15m',n(d.rsi))}${stat('OBV',n(d.obv))}${stat('نسبة الحجم',n(d.volume_ratio,2)+'x')}${stat('ATR',n(d.atr_pct,3)+'%')}${stat('الدعم',money(d.support))}${stat('المقاومة',money(d.resistance))}${stat('بعد الدعم',n(d.support_distance,2)+'%')}${stat('بعد المقاومة',n(d.resistance_distance,2)+'%')}${stat('حجم 24س',money(d.quoteVolume24h))}</div><h3>📊 قراءة الأطر الزمنية</h3><div class="tf"><div><b>15 دقيقة</b> RSI ${n(d.timeframes['15m'].rsi)} • OBV ${n(d.timeframes['15m'].obv)} • حجم ${n(d.timeframes['15m'].volume_ratio,2)}x</div><div><b>1 ساعة</b> RSI ${n(d.timeframes['1h'].rsi)} • OBV ${n(d.timeframes['1h'].obv)} • حجم ${n(d.timeframes['1h'].volume_ratio,2)}x</div><div><b>4 ساعات</b> RSI ${n(d.timeframes['4h'].rsi)} • OBV ${n(d.timeframes['4h'].obv)} • حجم ${n(d.timeframes['4h'].volume_ratio,2)}x</div><div><b>يومي</b> RSI ${n(d.timeframes['1d'].rsi)} • OBV ${n(d.timeframes['1d'].obv)} • حجم ${n(d.timeframes['1d'].volume_ratio,2)}x</div></div><h3>🔎 لماذا ظهرت؟</h3><p>${esc((d.why||[]).join(' • ')||'لا توجد إشارة حاسمة بعد')}</p><p class="note">التمويل مأخوذ من سوق العقود الآجلة إن كان متاحًا، بينما الرادار الأساسي يعمل على Binance Spot. التمويل السالب لا يعني وحده أن السعر سيرتفع.</p>`}catch(e){$('detail').innerHTML='<div class="empty red">تعذر جلب التفاصيل: '+esc(e.message)+'</div>'}}
function bindCards(){document.querySelectorAll('[data-symbol]').forEach(x=>x.onclick=()=>detail(x.dataset.symbol))}
$('scan').onclick=scan;$('af').onclick=af;$('bt').onclick=bt;$('close').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')};document.querySelectorAll('.mode').forEach(x=>x.onclick=()=>{document.querySelectorAll('.mode').forEach(y=>y.classList.remove('active'));x.classList.add('active');ACTIVE=x.dataset.mode;renderMode()});scan();ws();setInterval(ws,5000);setInterval(scan,180000);
