const $=id=>document.getElementById(id);let DATA=[];let ACTIVE='scalp';
async function j(u){const r=await fetch(u);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function num(v){return v==null?'—':Number(v).toFixed(1)}
function metric(n,v){return `<div class="metric"><span>${n}</span><b>${v??'—'}</b></div>`}
function stageClass(c){return c.stage==='CONFIRMED_EXPANSION'?'green':c.stage==='PRE_BREAKOUT'?'yellow':'blue'}
function stageAr(c){return c.stage==='CONFIRMED_EXPANSION'?'🟢 توسّع مؤكد':c.stage==='PRE_BREAKOUT'?'🟨 قبل الاختراق':c.stage==='STEALTH_ACCUMULATION'?'🟦 تجميع خفي':'👀 مراقبة'}
function card(c,extra=''){return `<article class="card"><div class="sym"><b>${esc(c.symbol)}</b><span class="stage ${stageClass(c)}">${stageAr(c)}</span></div><div class="scoreline"><span>🌙 قوة الفرصة المبكرة</span><b>${num(c.early_moon_ratio)}</b></div><div class="bar"><i style="width:${Math.min(100,Math.max(0,Number(c.early_moon_ratio)||0))}%"></i></div><div class="grid">${metric('📈 تجميع',num(c.accumulation))}${metric('🔥 تدفق',num(c.cvd))}${metric('🐋 حيتان',num(c.whale_hunter))}${metric('🌊 سيولة',num(c.liquidity))}</div>${extra}<p class="why">${(c.why||[]).slice(0,4).join(' • ')}</p></article>`}
function strategyScore(c,mode){let v=0,ch=Math.abs(Number(c.change24h)||0),early=Number(c.early_moon_ratio)||0,acc=Number(c.accumulation)||50,cvd=Number(c.cvd)||50,liq=Number(c.liquidity)||50,tf1=Number(c.tf_1h)||50,tf4=Number(c.tf_4h)||50,v5=Number(c.volume_5m_ratio)||1,v1=Number(c.volume_1m_ratio)||1;
 if(mode==='scalp') v=.30*early+.25*cvd+.20*Number(c.volume_pressure||50)+.15*liq+.10*Math.min(100,v5*50); else if(mode==='day') v=.30*early+.25*tf1+.20*acc+.15*cvd+.10*Number(c.breakout_ready||50); else if(mode==='swing') v=.35*tf4+.25*tf1+.20*acc+.10*Number(c.volume_profile||50)+.10*early; else v=.35*tf4+.25*acc+.15*liq+.15*early+.10*Number(c.volume_profile||50);
 if(mode!=='scalp'&&ch>18)v-=Math.min(15,(ch-18)*.7); if(mode==='scalp'&&ch>10)v-=Math.min(12,(ch-10)*1.2); return Math.max(0,Math.min(100,v));}
const notes={scalp:'يركّز على ضغط الشراء وحركة 5 دقائق والسيولة والطاقة المبكرة. مناسب للمراقبة السريعة، وليس ضمانًا لنتيجة الصفقة.',day:'يركّز على توازن الإشارة القصيرة مع اتجاه الساعة والاستعداد للاختراق.',swing:'يعطي وزنًا أكبر لاتجاه 1–4 ساعات والتجميع وموقع السعر داخل الحجم.',invest:'قائمة مراقبة أفقية 1–2 شهر؛ تعتمد على الاتجاه 4 ساعات وجودة التجميع والسيولة، وليست توقعًا مؤكدًا لسعر مستقبلي.'};
function renderStrategy(){let a=DATA.map(c=>({...c,_s:strategyScore(c,ACTIVE)})).sort((x,y)=>y._s-x._s).slice(0,5);$('strategyNote').textContent=notes[ACTIVE];$('strategyOut').innerHTML=a.map(c=>card(c,`<div class="strategy-score">درجة ${ACTIVE==='scalp'?'السكالب':ACTIVE==='day'?'التداول اليومي':ACTIVE==='swing'?'السوينغ':'المراقبة الاستثمارية'}: <b>${num(c._s)}</b></div>`)).join('')||'<div class="empty">لا توجد بيانات كافية.</div>';}
function renderLane(id,stage){let a=DATA.filter(c=>c.stage===stage).slice(0,5);$(id).innerHTML=a.map(c=>card(c)).join('')||'<div class="empty">لا توجد فرصة بهذه المرحلة.</div>'}
function render(){let q=$('search')?.value?.trim().toUpperCase();let st=$('stage')?.value;let a=DATA.filter(c=>(!q||c.symbol.includes(q))&&(!st||c.stage===st)).slice(0,5);$('results')&&($('results').innerHTML=a.map(c=>card(c)).join('')||'<article>لا توجد نتائج.</article>')}
async function scan(){ $('scan').disabled=true;$('scan').textContent='⏳ جاري الفحص…';try{const d=await j('/api/radar');DATA=d.results||[];$('bin').textContent=`Binance 🟢 • فحص أساسي: ${d.scanned_universe||0} زوج`;$('stats').textContent=`إشارات: ${DATA.length} • تحليل عميق: ${d.deep_analyzed||0} • ${d.scan_seconds||0}ث`;$('top5').innerHTML=(d.top5||DATA.slice(0,5)).slice(0,5).map(c=>card(c)).join('')||'<div class="empty">لا توجد إشارات قوية حاليًا.</div>';renderLane('stealth','STEALTH_ACCUMULATION');renderLane('prebreak','PRE_BREAKOUT');renderLane('confirmed','CONFIRMED_EXPANSION');renderStrategy();}catch(e){$('top5').innerHTML='<div class="empty red">تعذر تحميل الرادار: '+esc(e)+'</div>'}finally{$('scan').disabled=false;$('scan').textContent='🔄 فحص الآن';}}
async function ws(){try{const d=await j('/api/orderflow/status');$('ws').textContent=`WebSocket ${d.connected?'🟢 متصل':'🟡 ينتظر'} • ${d.symbols||0} رموز • ${d.events||0} أحداث`;}catch(e){$('ws').textContent='WebSocket 🔴'}}
function fmt(n){n=Number(n||0);if(n>=1e12)return(n/1e12).toFixed(2)+'T';if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(1)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return Math.round(n)}
function afCard(c){let state=c.acc_flow_state==='EARLY_ACC_FLOW'?'🔥 مبكرة':c.acc_flow_state==='ACC_FLOW_BUILDING'?'🟢 تتكوّن':c.acc_flow_state==='LATE_FLOW'?'⚠️ متأخرة':'👀 مراقبة';return `<article class="card"><div class="sym"><b>${esc(c.symbol)}</b><span class="stage ${c.acc_flow_state==='EARLY_ACC_FLOW'?'green':c.acc_flow_state==='LATE_FLOW'?'red':'yellow'}">${state}</span></div><div class="scoreline"><span>🏆 قوة التجميع + التدفق</span><b>${num(c.acc_flow_score)}</b></div><div class="grid">${metric('📈 تجميع',num(c.accumulation))}${metric('🔥 تدفق',num(c.flow_score))}${metric('🔥 CVD',num(c.cvd))}${metric('🐋 حيتان',num(c.whale_hunter))}${metric('💧 حجم/قيمة',c.volume_mcap_ratio+'%')}${metric('💵 القيمة السوقية','$'+fmt(c.market_cap_usd))}</div><p class="small">${esc(c.utility||'المنفعة غير متحقق منها')} • حجم 24س: $${fmt(c.volume_24h_usd)}</p><p class="why">${esc(c.core_reason||'')}</p></article>`}
async function accflowScan(){ $('af').disabled=true;$('af').textContent='⏳ جاري الفحص…';$('afout').innerHTML='<p class="small">نبحث عن أفضل 5 فقط بعد تطبيق مرشح الجودة.</p>';try{const d=await j('/api/accflow?core_only=true');if(d.status!=='ok')throw Error(d.error||'scanner error');$('afsummary').innerHTML=`<span>🏦 المؤهل: ${d.matched}</span><span>🔬 تعميق: ${d.deep_checked}</span><span>⏱️ ${d.seconds}ث</span><span>🛡️ قيمة سوقية ≥ $5B</span><span>💧 حجم/قيمة ≥ ${d.core_filter.min_volume_mcap_pct}%</span>`;$('afout').innerHTML=(d.top10||[]).slice(0,5).map(afCard).join('')||'<p>لا توجد عملات مطابقة حاليًا.</p>'}catch(e){$('afout').innerHTML='<p class="red">فشل الفحص: '+esc(e)+'</p>'}finally{$('af').disabled=false;$('af').textContent='فحص أفضل العملات الأساسية'}}
async function backtest(){ $('bt').disabled=true;$('bt').textContent='⏳ جاري الاختبار…';$('btout').innerHTML='<p class="small">قد يستغرق عدة دقائق.</p>';try{const d=await j('/api/backtest/top?top_n=50&days=30');if(d.status!=='ok')throw Error(d.error||'backtest error');let p=(d.pattern_leaderboard||[]).slice(0,5).map(x=>`<div class="row"><b>${esc(x.pattern)}</b><span>${x.signals} إشارة</span><span>${x.win_rate}% نجاح</span><span>${x.avg_return_pct}% متوسط</span></div>`).join('');$('btout').innerHTML=`<p>اختُبرت ${d.tested}/${d.top_n} عملة خلال ${d.seconds}ث</p><h3>🏆 أهم 5 تركيبات تاريخية</h3>${p}`;}catch(e){$('btout').innerHTML='<p class="red">فشل الاختبار: '+esc(e)+'</p>'}finally{$('bt').disabled=false;$('bt').textContent='اختبر أفضل 50'}}
$('scan').onclick=scan;$('bt').onclick=backtest;$('af').onclick=accflowScan;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');ACTIVE=b.dataset.mode;renderStrategy()});scan();ws();setInterval(ws,5000);setInterval(scan,120000);
